import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter=({substes:["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={inter.classname}
      >
      <div className="max-w-3xl max-auto p-4">
      <Navbar/>
      
      <div className="mt-8"> 
      {children}
      </div>
      </div>
      
      </body>
    </html>
  );
}
